apiVersion: apps/v1
kind: Deployment
metadata:
  name: artikli-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artikli
  template:
    metadata:
      labels:
        app: artikli
    spec:
      containers:
        - image: fdemsar/artikli:2022-12-30-02-04-51
          name: artikli
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://snuffleupagus.db.elephantsql.com:5432/zismkcwt
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: zismkcwt
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass-artikli
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 70
            periodSeconds: 3
          readinessProbe:
              httpGet:
                path: /health/ready
                port: server
              initialDelaySeconds: 40
              periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: artikli
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: artikli
